---
name: run tests
"on":
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.x, 3.12-dev]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install -r requirements.txt
          pip install pycodestyle pyflakes pylint dlint pyupgrade
      - name: Run tests
        env:
          RUN_ONLINETESTS: 1
        run: |
          python3 -m unittest
